apiVersion: v1
kind: Pod
metadata:
  name: test-privileged
  namespace: securebank
spec:
  containers:
    - name: priv
      image: alpine:3.20
      command: ["sleep", "3600"]
      securityContext:
        privileged: true