apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: securebank-api
  app.kubernetes.io/part-of: securebank

images:
  - name: securebank
    newName: ghcr.io/stayrelevantid/securebank-api
    newTag: latest
