apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: securebank-jwt
  namespace: securebank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: securebank-jwt
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: securebank/jwt-secret
