apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securebank
resources:
  - ../../base

nameSuffix: -uat

replicas:
  - name: securebank-api
    count: 2

patches:
  - path: deployment-patch.yaml
